// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923110055_AddProductCategories")]
    partial class AddProductCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Entities.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("Api.Entities.HouseholdInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("HouseholdInvitations");
                });

            modelBuilder.Entity("Api.Entities.HouseholdMember", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("HouseholdId", "UserId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("HouseholdMembers");
                });

            modelBuilder.Entity("Api.Entities.OffCategoryMapping", b =>
                {
                    b.Property<string>("OffTag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("OffTag");

                    b.HasIndex("CategoryId");

                    b.ToTable("OffCategoryMappings");

                    b.HasData(
                        new
                        {
                            OffTag = "en:ground-meats",
                            CategoryId = 1,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:meats",
                            CategoryId = 2,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:beef",
                            CategoryId = 2,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:beef-steaks",
                            CategoryId = 2,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:pork",
                            CategoryId = 2,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:veal-meat",
                            CategoryId = 2,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:lamb-meat",
                            CategoryId = 2,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:poultries",
                            CategoryId = 3,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:chickens",
                            CategoryId = 3,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:chicken-breasts",
                            CategoryId = 3,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:turkeys",
                            CategoryId = 3,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:fishes",
                            CategoryId = 4,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:seafood",
                            CategoryId = 4,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:crustaceans",
                            CategoryId = 4,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:smoked-salmons",
                            CategoryId = 4,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:prepared-meats",
                            CategoryId = 5,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:hams",
                            CategoryId = 5,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:sausages",
                            CategoryId = 5,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:dry-sausages",
                            CategoryId = 5,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:bacon",
                            CategoryId = 5,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:eggs",
                            CategoryId = 6,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:chicken-eggs",
                            CategoryId = 6,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:milks",
                            CategoryId = 7,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:fresh-milks",
                            CategoryId = 7,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:uht-milks",
                            CategoryId = 8,
                            Priority = 10
                        },
                        new
                        {
                            OffTag = "en:yogurts",
                            CategoryId = 9,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:dairy-desserts",
                            CategoryId = 9,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:fermented-milk-products",
                            CategoryId = 9,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:fresh-cheeses",
                            CategoryId = 10,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:cream-cheeses",
                            CategoryId = 10,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:mozzarella",
                            CategoryId = 10,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:cheeses",
                            CategoryId = 11,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:soft-cheeses",
                            CategoryId = 11,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:camemberts",
                            CategoryId = 11,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:bries",
                            CategoryId = 11,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:reblochon",
                            CategoryId = 11,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:munster",
                            CategoryId = 11,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:saint-nectaire",
                            CategoryId = 11,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:blue-veined-cheeses",
                            CategoryId = 11,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:roquefort-cheeses",
                            CategoryId = 11,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:goat-cheeses",
                            CategoryId = 11,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:hard-cheeses",
                            CategoryId = 12,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:uncooked-pressed-cheeses",
                            CategoryId = 12,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:comte",
                            CategoryId = 12,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:emmentaler",
                            CategoryId = 12,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:parmigiano-reggiano",
                            CategoryId = 12,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:grana-padano",
                            CategoryId = 12,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:beaufort",
                            CategoryId = 12,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:cantal",
                            CategoryId = 12,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:morbier",
                            CategoryId = 12,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:raclette",
                            CategoryId = 12,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:gouda",
                            CategoryId = 12,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:cheddar-cheese",
                            CategoryId = 12,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:grated-cheese",
                            CategoryId = 12,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:butters",
                            CategoryId = 13,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:salted-butters",
                            CategoryId = 13,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:creams",
                            CategoryId = 14,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:sour-creams",
                            CategoryId = 14,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:fruits",
                            CategoryId = 15,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:fresh-fruits",
                            CategoryId = 15,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:vegetables",
                            CategoryId = 16,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:fresh-vegetables",
                            CategoryId = 16,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:leaf-vegetables",
                            CategoryId = 17,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:lettuces",
                            CategoryId = 17,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:aromatic-plants",
                            CategoryId = 17,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:breads",
                            CategoryId = 18,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:sliced-breads",
                            CategoryId = 18,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:viennoiseries",
                            CategoryId = 18,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:meals",
                            CategoryId = 19,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:fresh-meals",
                            CategoryId = 19,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:pizzas",
                            CategoryId = 19,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:sandwiches",
                            CategoryId = 19,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:frozen-foods",
                            CategoryId = 21,
                            Priority = 10
                        },
                        new
                        {
                            OffTag = "en:frozen-vegetables",
                            CategoryId = 21,
                            Priority = 10
                        },
                        new
                        {
                            OffTag = "en:ice-creams",
                            CategoryId = 21,
                            Priority = 10
                        },
                        new
                        {
                            OffTag = "en:canned-foods",
                            CategoryId = 22,
                            Priority = 10
                        },
                        new
                        {
                            OffTag = "en:canned-vegetables",
                            CategoryId = 22,
                            Priority = 10
                        },
                        new
                        {
                            OffTag = "en:canned-fishes",
                            CategoryId = 22,
                            Priority = 10
                        },
                        new
                        {
                            OffTag = "en:dried-products",
                            CategoryId = 23,
                            Priority = 10
                        },
                        new
                        {
                            OffTag = "en:pastas",
                            CategoryId = 23,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:rices",
                            CategoryId = 23,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:cereals-and-their-products",
                            CategoryId = 23,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:flours",
                            CategoryId = 23,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:legumes",
                            CategoryId = 23,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:pulses",
                            CategoryId = 23,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:breakfast-cereals",
                            CategoryId = 23,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:biscuits",
                            CategoryId = 23,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:snacks",
                            CategoryId = 23,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:chocolates",
                            CategoryId = 23,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:condiments",
                            CategoryId = 24,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:sauces",
                            CategoryId = 24,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:mustards",
                            CategoryId = 24,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:ketchup",
                            CategoryId = 24,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:salad-dressings",
                            CategoryId = 24,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:jams",
                            CategoryId = 24,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:honeys",
                            CategoryId = 24,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:spreads",
                            CategoryId = 24,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:vegetable-oils",
                            CategoryId = 24,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:beverages",
                            CategoryId = 25,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:waters",
                            CategoryId = 25,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:sodas",
                            CategoryId = 25,
                            Priority = 0
                        },
                        new
                        {
                            OffTag = "en:fruit-juices",
                            CategoryId = 25,
                            Priority = 0
                        });
                });

            modelBuilder.Entity("Api.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DefaultShelfLifeDays")
                        .HasColumnType("integer");

                    b.Property<string>("ExpiryKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ProductCategories", t =>
                        {
                            t.HasCheckConstraint("CK_ProductCategories_DefaultShelfLifeDays", "\"DefaultShelfLifeDays\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ground-meat",
                            DefaultShelfLifeDays = 1,
                            ExpiryKind = "UseBy",
                            Name = "Viande hachée"
                        },
                        new
                        {
                            Id = 2,
                            Code = "fresh-meat",
                            DefaultShelfLifeDays = 3,
                            ExpiryKind = "UseBy",
                            Name = "Viande fraîche"
                        },
                        new
                        {
                            Id = 3,
                            Code = "poultry",
                            DefaultShelfLifeDays = 2,
                            ExpiryKind = "UseBy",
                            Name = "Volaille"
                        },
                        new
                        {
                            Id = 4,
                            Code = "fish-seafood",
                            DefaultShelfLifeDays = 2,
                            ExpiryKind = "UseBy",
                            Name = "Poisson, fruits de mer"
                        },
                        new
                        {
                            Id = 5,
                            Code = "cold-cuts",
                            DefaultShelfLifeDays = 7,
                            ExpiryKind = "UseBy",
                            Name = "Charcuterie"
                        },
                        new
                        {
                            Id = 6,
                            Code = "eggs",
                            DefaultShelfLifeDays = 21,
                            ExpiryKind = "BestBefore",
                            Name = "Œufs"
                        },
                        new
                        {
                            Id = 7,
                            Code = "fresh-milk",
                            DefaultShelfLifeDays = 7,
                            ExpiryKind = "UseBy",
                            Name = "Lait frais"
                        },
                        new
                        {
                            Id = 8,
                            Code = "uht-milk",
                            DefaultShelfLifeDays = 90,
                            ExpiryKind = "BestBefore",
                            Name = "Lait UHT"
                        },
                        new
                        {
                            Id = 9,
                            Code = "yogurts",
                            DefaultShelfLifeDays = 21,
                            ExpiryKind = "UseBy",
                            Name = "Yaourts, desserts lactés"
                        },
                        new
                        {
                            Id = 10,
                            Code = "fresh-cheese",
                            DefaultShelfLifeDays = 7,
                            ExpiryKind = "UseBy",
                            Name = "Fromage frais"
                        },
                        new
                        {
                            Id = 11,
                            Code = "soft-cheese",
                            DefaultShelfLifeDays = 14,
                            ExpiryKind = "UseBy",
                            Name = "Fromage à pâte molle"
                        },
                        new
                        {
                            Id = 12,
                            Code = "hard-cheese",
                            DefaultShelfLifeDays = 30,
                            ExpiryKind = "BestBefore",
                            Name = "Fromage à pâte dure"
                        },
                        new
                        {
                            Id = 13,
                            Code = "butter",
                            DefaultShelfLifeDays = 60,
                            ExpiryKind = "BestBefore",
                            Name = "Beurre"
                        },
                        new
                        {
                            Id = 14,
                            Code = "cream",
                            DefaultShelfLifeDays = 14,
                            ExpiryKind = "UseBy",
                            Name = "Crème"
                        },
                        new
                        {
                            Id = 15,
                            Code = "fruits",
                            DefaultShelfLifeDays = 7,
                            ExpiryKind = "BestBefore",
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 16,
                            Code = "vegetables",
                            DefaultShelfLifeDays = 7,
                            ExpiryKind = "BestBefore",
                            Name = "Légumes"
                        },
                        new
                        {
                            Id = 17,
                            Code = "leafy-greens",
                            DefaultShelfLifeDays = 4,
                            ExpiryKind = "BestBefore",
                            Name = "Salade, herbes"
                        },
                        new
                        {
                            Id = 18,
                            Code = "bread",
                            DefaultShelfLifeDays = 3,
                            ExpiryKind = "BestBefore",
                            Name = "Pain"
                        },
                        new
                        {
                            Id = 19,
                            Code = "ready-meals",
                            DefaultShelfLifeDays = 3,
                            ExpiryKind = "UseBy",
                            Name = "Traiteur, plats préparés"
                        },
                        new
                        {
                            Id = 20,
                            Code = "leftovers",
                            DefaultShelfLifeDays = 3,
                            ExpiryKind = "UseBy",
                            Name = "Restes faits maison"
                        },
                        new
                        {
                            Id = 21,
                            Code = "frozen",
                            DefaultShelfLifeDays = 180,
                            ExpiryKind = "BestBefore",
                            Name = "Surgelés"
                        },
                        new
                        {
                            Id = 22,
                            Code = "canned",
                            DefaultShelfLifeDays = 730,
                            ExpiryKind = "BestBefore",
                            Name = "Conserves"
                        },
                        new
                        {
                            Id = 23,
                            Code = "dry-goods",
                            DefaultShelfLifeDays = 365,
                            ExpiryKind = "BestBefore",
                            Name = "Épicerie sèche"
                        },
                        new
                        {
                            Id = 24,
                            Code = "condiments",
                            DefaultShelfLifeDays = 90,
                            ExpiryKind = "BestBefore",
                            Name = "Sauces, condiments"
                        },
                        new
                        {
                            Id = 25,
                            Code = "drinks",
                            DefaultShelfLifeDays = 30,
                            ExpiryKind = "BestBefore",
                            Name = "Boissons"
                        },
                        new
                        {
                            Id = 26,
                            Code = "other",
                            DefaultShelfLifeDays = 7,
                            ExpiryKind = "BestBefore",
                            Name = "Autre"
                        });
                });

            modelBuilder.Entity("Api.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Api.Entities.HouseholdInvitation", b =>
                {
                    b.HasOne("Api.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Entities.Household", "Household")
                        .WithMany("Invitations")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Api.Entities.HouseholdMember", b =>
                {
                    b.HasOne("Api.Entities.Household", "Household")
                        .WithMany("Members")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Entities.User", "User")
                        .WithOne("Membership")
                        .HasForeignKey("Api.Entities.HouseholdMember", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Entities.OffCategoryMapping", b =>
                {
                    b.HasOne("Api.Entities.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Api.Entities.RefreshToken", b =>
                {
                    b.HasOne("Api.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Api.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Api.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Api.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Entities.Household", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Api.Entities.User", b =>
                {
                    b.Navigation("Membership");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
